site_name: Developers
theme:
  name: material
  language: ru
  logo: assets/koshelek.svg
  palette:
    - scheme: default
      primary: plum
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: pink
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode

extra:
  homepage: https://developers.cardsmobile.ru
  alternate:
    - name: English
    - link: /en/
    - lang: en
    - name: Русский
    - link: /ru/
    - lang: ru