site_name: Material for MkDocs
theme:
  name: material
  language: ru
  features:
    - navigation.sections
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: pink
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode
nav:
  - OpenAPI: new.md