site_name: Material for MkDocs
repo_url: https://github.com/andwr/mkdocs-material
repo_name: andwr/mkdocs-material
edit_uri: edit/main/docs
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: pink
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode
nav:
  - OpenAPI: new.md
plugins:
  - search
  - neoteroi.mkdocsoad